version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4445:4445"
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "4445", "--workers", "1"]
    volumes:
      - ./images:/tmp_images
      - ./ollama:/root/.ollama
    networks:
      - main_network
    restart: always
  ollama:
    image: ollama/ollama:latest
    networks:
      - main_network
    ports:
      - "11434:11434"
    volumes:
      - ./images:/tmp_images
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

networks:
  main_network: